components:
  contentService:
    remoteStorage:
      kind: gcloud
      backupTrail:
        enabled: true
        maxLength: 2
      gcloud:
        credentialsFileUpload: true
        credentialsFile: /credentials/service-account.json
        projectId: gitpod-dev
        region: europe-west1
        tmpdir: /mnt/sync-tmp
        parallelUpload: 6
    volumes:
      - name: gcloud-creds
        secret:
          secretName: remote-storage-gcloud
    volumeMounts:
    - mountPath: /credentials
      name: gcloud-creds
  wsManager:
    volumes:
    - name: gcloud-creds
      secret:
        secretName: remote-storage-gcloud
    volumeMounts:
    - mountPath: /credentials
      name: gcloud-creds
  wsDaemon:
    volumes:
    - name: gcloud-creds
      secret:
        secretName: remote-storage-gcloud
    volumeMounts:
    - mountPath: /credentials
      name: gcloud-creds

minio:
  enabled: false
